### ISSUE TITLE
Build Failure: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by baaguigui** [travelpayouts/white-label-app-ios#1]
Hi,
I am experiencing an issue when building the project on Xcode. The build process fails with the following error: 
`Command PhaseScriptExecution failed with a nonzero exit code`. 
- Xcode version 15.3

Here is a screenshot of the error:
![10](https://github.com/travelpayouts/white-label-app-ios/assets/65304499/319b5614-90cb-48b8-ae46-2a03919c9d55)

I would appreciate any help in resolving this issue. Thank you!

**Comment by tpsupport** [comment]
Hi,  
Thanks for reaching out!
Kindly share your partner marker (ID) and the app version to support@travelpayouts.com

**Comment by baaguigui** [comment]
Hi,

I have sent the partner marker (ID) and app version as requested.

Thanks,

**Comment by baaguigui** [comment]
Hi,

I wanted to update you that I have resolved the issue. The problem was related to the PATH environment variable in my shell configuration. After updating the PATH correctly, the build issue has been fixed.

Thank you for your assistance.

**Comment by tpsupport** [comment]
Hi,

Thank you for the update, we're glad to hear this!
