### ISSUE TITLE
Asset Validation Failed - Xcode Upload Error

### ISSUE THREAD

**Issue by baaguigui** [travelpayouts/white-label-app-ios#3]
When trying to upload the app to Apple Store Connect via Xcode as an update to my previous app, which supports both iPhone and iPad, I encountered the following error:

![err](https://github.com/travelpayouts/white-label-app-ios/assets/65304499/0749eef0-8d04-4110-ab01-abdf3e11f6d0)

Please help me resolve this issue and clarify if there are any additional settings that need to be modified in the project.

**Comment by tpsupport** [comment]
Hi,

Could you please contact our support team at support@travelpayouts.com and send the configuration file? We'll check the details.
