### ISSUE TITLE
Missing Privacy Manifests for Third-Party SDKs Required by Apple (ITMS-91061)

### ISSUE THREAD

**Issue by baaguigui** [travelpayouts/white-label-app-ios#4]
Hello,

I’ve received a notification from Apple during the App Store review process regarding the usage of third-party SDKs in my app. The following SDKs have been flagged as privacy-impacting, and Apple requires these SDKs to include a privacy manifest starting from November 12, 2024:

	1.	Kingfisher.framework/Kingfisher
	2.	Lottie.framework/Lottie
	3.	SnapKit.framework/SnapKit

The specific error code is ITMS-91061: Missing privacy manifest.

To comply with Apple’s upcoming requirements, could you please update the SDKs used in this project to versions that include the required privacy manifest files?

For more details, Apple has provided information on this policy here: [Apple Third-Party SDK Requirements](https://developer.apple.com/support/third-party-SDK-requirements).

Thank you for your assistance in resolving this issue.

![App Store review](https://github.com/user-attachments/assets/e1179d98-3fe5-4d66-9db5-c5bf5cb09463)

**Comment by tpsupport** [comment]
Hello,

There’s no action required on this at the moment. Please note that this is not yet part of the review process; it's related to uploading the build to App Store Connect.
