### ISSUE TITLE
Language not changing for certain parts of the UI

### ISSUE THREAD

**Issue by baaguigui** [travelpayouts/white-label-app-ios#6]
Hello,
When changing the language of the app to languages other than Russian, certain UI elements remain untranslated. Specifically, the phrases “Ищем авиабилеты…” and “Ищем отели…” do not change when switching the app’s language.

![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-06 at 08 08 03](https://github.com/user-attachments/assets/0d3caa8d-2904-457a-b2c3-d81edf34bed9)

![Simulator Screenshot - iPhone 16 Pro Max - 2024-10-06 at 08 24 06](https://github.com/user-attachments/assets/8b9f35c5-2d14-47e1-9dca-a04a7df5fc91)

I would appreciate it if this could be fixed in a future update.

**Comment by tpsupport** [comment]
Hello, 

Thank you for the report and for your patience! 

We have successfully fixed this issue in the latest update. 

Thanks again!
